services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      - APP_SECRET=REDACTED
      - FLAG=srdnlen{REDACTED}
    networks:
      - internal_net

  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=5000
      - PORT=80
    networks:
      - internal_net

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - GATEWAY_URL=http://gateway
    networks:
      - internal_net
    ports:
      - "8000:80"

networks:
  internal_net: